/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Returns 200 as long as the process is serving. Does not touch the database.
         */
        get: operations["getHealthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Round-trip probe
         * @description Exercises the full request path — generated handler, sqlc query, Postgres —
         *     and returns the database's own clock. Exists to prove the toolchain end to
         *     end; it carries no domain meaning.
         */
        get: operations["getPing"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthStatus: {
            /**
             * @description Always `ok`; a non-200 status is the real signal.
             * @enum {string}
             */
            status: "ok";
        };
        PingResult: {
            /**
             * Format: date-time
             * @description Current time as reported by Postgres, not by the API process.
             */
            now: string;
            /**
             * @description Always `ok`; the 503 response covers the failure case.
             * @enum {string}
             */
            database: "ok";
        };
        Error: {
            /**
             * @description Stable, machine-readable error code.
             * @example database_unavailable
             */
            code: string;
            /** @description Human-readable detail. Localised from the Go message catalogue (M2 onward). */
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The process is alive. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    getPing: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The database answered. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PingResult"];
                };
            };
            /** @description The database did not answer. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
