// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: families.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addFamilyMember = `-- name: AddFamilyMember :one
INSERT INTO family_members (family_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (family_id, user_id) DO UPDATE
SET role = family_members.role
RETURNING family_id, user_id, role, joined_at
`

type AddFamilyMemberParams struct {
	FamilyID pgtype.UUID `json:"family_id"`
	UserID   pgtype.UUID `json:"user_id"`
	Role     FamilyRole  `json:"role"`
}

func (q *Queries) AddFamilyMember(ctx context.Context, arg AddFamilyMemberParams) (FamilyMember, error) {
	row := q.db.QueryRow(ctx, addFamilyMember, arg.FamilyID, arg.UserID, arg.Role)
	var i FamilyMember
	err := row.Scan(
		&i.FamilyID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const createFamily = `-- name: CreateFamily :one

INSERT INTO families (name)
VALUES ($1)
RETURNING id AS family_id, name, default_currency, created_at
`

type CreateFamilyRow struct {
	FamilyID        pgtype.UUID        `json:"family_id"`
	Name            string             `json:"name"`
	DefaultCurrency string             `json:"default_currency"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

// Families and membership.
//
// `families` is the awkward table for the tenancy invariant: its own id *is*
// the tenant key, so there is no family_id column to filter on. The two
// queries that read and write a family row therefore scope themselves through
// family_members, which is stronger than a primary-key lookup — the caller
// proves membership rather than asserting it — and is what the `family-scoped`
// vet rule is checking for.
// Called once per account that signs in without an existing membership. The
// returned id is the tenant every later query is scoped by.
func (q *Queries) CreateFamily(ctx context.Context, name string) (CreateFamilyRow, error) {
	row := q.db.QueryRow(ctx, createFamily, name)
	var i CreateFamilyRow
	err := row.Scan(
		&i.FamilyID,
		&i.Name,
		&i.DefaultCurrency,
		&i.CreatedAt,
	)
	return i, err
}

const getFamily = `-- name: GetFamily :one
SELECT f.id, f.name, f.default_currency, f.created_at
FROM families f
         JOIN family_members m ON m.family_id = f.id
WHERE f.id = $1
  AND m.user_id = $2
`

type GetFamilyParams struct {
	FamilyID pgtype.UUID `json:"family_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

// Scoped through family_members rather than by primary key alone.
//
// `families` is the one tenant table with no family_id column of its own — its
// id *is* the tenant key — so "filter on family_id" has to mean something else
// here. Joining membership is the honest reading: the caller proves they are
// in the family they are asking about, instead of the query trusting a claim
// the session made. It is also what lets the `family-scoped` vet rule see a
// real scope instead of a bare primary-key lookup.
func (q *Queries) GetFamily(ctx context.Context, arg GetFamilyParams) (Family, error) {
	row := q.db.QueryRow(ctx, getFamily, arg.FamilyID, arg.UserID)
	var i Family
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DefaultCurrency,
		&i.CreatedAt,
	)
	return i, err
}

const getFamilyMembership = `-- name: GetFamilyMembership :one
SELECT family_id, user_id, role, joined_at
FROM family_members
WHERE family_id = $1
  AND user_id = $2
`

type GetFamilyMembershipParams struct {
	FamilyID pgtype.UUID `json:"family_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

// The authorisation primitive: does this user belong to this family, and as
// what. Every family-scoped handler resolves it from the session before it
// touches anything else.
func (q *Queries) GetFamilyMembership(ctx context.Context, arg GetFamilyMembershipParams) (FamilyMember, error) {
	row := q.db.QueryRow(ctx, getFamilyMembership, arg.FamilyID, arg.UserID)
	var i FamilyMember
	err := row.Scan(
		&i.FamilyID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const getFirstFamilyForUser = `-- name: GetFirstFamilyForUser :one
SELECT family_id, role
FROM family_members
WHERE user_id = $1
ORDER BY joined_at, family_id
LIMIT 1
`

type GetFirstFamilyForUserRow struct {
	FamilyID pgtype.UUID `json:"family_id"`
	Role     FamilyRole  `json:"role"`
}

// One family exists in practice, but the schema is multi-tenant from day one
// (SPEC 2, "Audience"), so sign-in picks the earliest membership deterministically
// rather than assuming there is exactly one.
func (q *Queries) GetFirstFamilyForUser(ctx context.Context, userID pgtype.UUID) (GetFirstFamilyForUserRow, error) {
	row := q.db.QueryRow(ctx, getFirstFamilyForUser, userID)
	var i GetFirstFamilyForUserRow
	err := row.Scan(&i.FamilyID, &i.Role)
	return i, err
}

const listFamilyMembers = `-- name: ListFamilyMembers :many
SELECT m.family_id,
       m.user_id,
       m.role,
       m.joined_at,
       u.email,
       u.display_name,
       u.avatar_url,
       u.last_seen_at
FROM family_members m
         JOIN users u ON u.id = m.user_id
WHERE m.family_id = $1
ORDER BY m.joined_at, m.user_id
`

type ListFamilyMembersRow struct {
	FamilyID    pgtype.UUID        `json:"family_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Role        FamilyRole         `json:"role"`
	JoinedAt    pgtype.Timestamptz `json:"joined_at"`
	Email       string             `json:"email"`
	DisplayName string             `json:"display_name"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
	LastSeenAt  pgtype.Timestamptz `json:"last_seen_at"`
}

func (q *Queries) ListFamilyMembers(ctx context.Context, familyID pgtype.UUID) ([]ListFamilyMembersRow, error) {
	rows, err := q.db.Query(ctx, listFamilyMembers, familyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFamilyMembersRow{}
	for rows.Next() {
		var i ListFamilyMembersRow
		if err := rows.Scan(
			&i.FamilyID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
			&i.Email,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFamilyMember = `-- name: RemoveFamilyMember :execrows
DELETE
FROM family_members
WHERE family_id = $1
  AND user_id = $2
  AND role = 'member'
`

type RemoveFamilyMemberParams struct {
	FamilyID pgtype.UUID `json:"family_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

// Owners are deliberately not removable through this path: demoting or
// removing the last owner would leave the family unadministrable, and there is
// no role-change endpoint in M1. Zero affected rows is the caller's signal.
func (q *Queries) RemoveFamilyMember(ctx context.Context, arg RemoveFamilyMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeFamilyMember, arg.FamilyID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateFamily = `-- name: UpdateFamily :one
UPDATE families
SET name             = coalesce($1, name),
    default_currency = coalesce($2, default_currency)
WHERE id = $3
  AND EXISTS (SELECT 1
              FROM family_members m
              WHERE m.family_id = families.id
                AND m.user_id = $4)
RETURNING id, name, default_currency, created_at
`

type UpdateFamilyParams struct {
	Name            pgtype.Text `json:"name"`
	DefaultCurrency pgtype.Text `json:"default_currency"`
	FamilyID        pgtype.UUID `json:"family_id"`
	UserID          pgtype.UUID `json:"user_id"`
}

// Partial update: an argument left NULL leaves its column alone, so the caller
// does not have to read-modify-write the whole row.
//
// Membership-scoped for the same reason as GetFamily above.
func (q *Queries) UpdateFamily(ctx context.Context, arg UpdateFamilyParams) (Family, error) {
	row := q.db.QueryRow(ctx, updateFamily,
		arg.Name,
		arg.DefaultCurrency,
		arg.FamilyID,
		arg.UserID,
	)
	var i Family
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DefaultCurrency,
		&i.CreatedAt,
	)
	return i, err
}
