// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invites.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptInvite = `-- name: AcceptInvite :one
UPDATE family_invites
SET accepted_at         = now(),
    accepted_by_user_id = $2
WHERE token_hash = $1
  AND accepted_at IS NULL
  AND revoked_at IS NULL
  AND expires_at > now()
RETURNING id, family_id
`

type AcceptInviteParams struct {
	TokenHash        []byte      `json:"token_hash"`
	AcceptedByUserID pgtype.UUID `json:"accepted_by_user_id"`
}

type AcceptInviteRow struct {
	ID       pgtype.UUID `json:"id"`
	FamilyID pgtype.UUID `json:"family_id"`
}

// Single-use, enforced by the statement rather than by the caller: the
// predicate and the write happen in one round trip, so two invitees racing on
// the same link cannot both win. No row means expired, revoked or already used.
func (q *Queries) AcceptInvite(ctx context.Context, arg AcceptInviteParams) (AcceptInviteRow, error) {
	row := q.db.QueryRow(ctx, acceptInvite, arg.TokenHash, arg.AcceptedByUserID)
	var i AcceptInviteRow
	err := row.Scan(&i.ID, &i.FamilyID)
	return i, err
}

const createFamilyInvite = `-- name: CreateFamilyInvite :one

INSERT INTO family_invites (family_id, token_hash, created_by, expires_at)
VALUES ($1, $2, $3,
        $4)
RETURNING id, family_id, created_by, created_at, expires_at,
          accepted_at, accepted_by_user_id, revoked_at
`

type CreateFamilyInviteParams struct {
	FamilyID  pgtype.UUID        `json:"family_id"`
	TokenHash []byte             `json:"token_hash"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type CreateFamilyInviteRow struct {
	ID               pgtype.UUID        `json:"id"`
	FamilyID         pgtype.UUID        `json:"family_id"`
	CreatedBy        pgtype.UUID        `json:"created_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	AcceptedAt       pgtype.Timestamptz `json:"accepted_at"`
	AcceptedByUserID pgtype.UUID        `json:"accepted_by_user_id"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
}

// Family invites.
//
// An owner generates a single-use link; the invitee signs in with Google and
// joins. There is no email anywhere in the system (SPEC 2, "Notifications"),
// so the link travels over whatever channel the family already uses.
//
// Only the SHA-256 of the token is stored. A database dump therefore yields no
// usable invite links.
func (q *Queries) CreateFamilyInvite(ctx context.Context, arg CreateFamilyInviteParams) (CreateFamilyInviteRow, error) {
	row := q.db.QueryRow(ctx, createFamilyInvite,
		arg.FamilyID,
		arg.TokenHash,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	var i CreateFamilyInviteRow
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedByUserID,
		&i.RevokedAt,
	)
	return i, err
}

const getInviteByTokenHash = `-- name: GetInviteByTokenHash :one
SELECT i.id,
       i.family_id,
       i.expires_at,
       i.accepted_at,
       i.revoked_at,
       f.name AS family_name
FROM family_invites i
         JOIN families f ON f.id = i.family_id
WHERE i.token_hash = $1
`

type GetInviteByTokenHashRow struct {
	ID         pgtype.UUID        `json:"id"`
	FamilyID   pgtype.UUID        `json:"family_id"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	AcceptedAt pgtype.Timestamptz `json:"accepted_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	FamilyName string             `json:"family_name"`
}

// Backs the public `/invites/{token}` preview, so it returns the family's name
// and nothing else about it: an invite link must be enough to see who invited
// you, and never enough to see their inventory.
func (q *Queries) GetInviteByTokenHash(ctx context.Context, tokenHash []byte) (GetInviteByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getInviteByTokenHash, tokenHash)
	var i GetInviteByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.RevokedAt,
		&i.FamilyName,
	)
	return i, err
}

const listFamilyInvites = `-- name: ListFamilyInvites :many
SELECT id, family_id, created_by, created_at, expires_at,
       accepted_at, accepted_by_user_id, revoked_at
FROM family_invites
WHERE family_id = $1
ORDER BY created_at DESC
`

type ListFamilyInvitesRow struct {
	ID               pgtype.UUID        `json:"id"`
	FamilyID         pgtype.UUID        `json:"family_id"`
	CreatedBy        pgtype.UUID        `json:"created_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	AcceptedAt       pgtype.Timestamptz `json:"accepted_at"`
	AcceptedByUserID pgtype.UUID        `json:"accepted_by_user_id"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) ListFamilyInvites(ctx context.Context, familyID pgtype.UUID) ([]ListFamilyInvitesRow, error) {
	rows, err := q.db.Query(ctx, listFamilyInvites, familyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFamilyInvitesRow{}
	for rows.Next() {
		var i ListFamilyInvitesRow
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.AcceptedByUserID,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeFamilyInvite = `-- name: RevokeFamilyInvite :execrows
UPDATE family_invites
SET revoked_at = now()
WHERE id = $1
  AND family_id = $2
  AND revoked_at IS NULL
  AND accepted_at IS NULL
`

type RevokeFamilyInviteParams struct {
	ID       pgtype.UUID `json:"id"`
	FamilyID pgtype.UUID `json:"family_id"`
}

func (q *Queries) RevokeFamilyInvite(ctx context.Context, arg RevokeFamilyInviteParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeFamilyInvite, arg.ID, arg.FamilyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
