// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: people.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archivePerson = `-- name: ArchivePerson :execrows
UPDATE people
SET archived_at = now(),
    updated_at  = now()
WHERE id = $1
  AND family_id = $2
  AND archived_at IS NULL
`

type ArchivePersonParams struct {
	ID       pgtype.UUID `json:"id"`
	FamilyID pgtype.UUID `json:"family_id"`
}

func (q *Queries) ArchivePerson(ctx context.Context, arg ArchivePersonParams) (int64, error) {
	result, err := q.db.Exec(ctx, archivePerson, arg.ID, arg.FamilyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createPerson = `-- name: CreatePerson :one

INSERT INTO people (family_id, name, birthdate, user_id, is_child, avatar_url)
VALUES ($1, $2, $3,
        $4, $5, $6)
RETURNING id, family_id, name, birthdate, user_id, is_child, avatar_url, created_at, updated_at, archived_at
`

type CreatePersonParams struct {
	FamilyID  pgtype.UUID `json:"family_id"`
	Name      string      `json:"name"`
	Birthdate pgtype.Date `json:"birthdate"`
	UserID    pgtype.UUID `json:"user_id"`
	IsChild   bool        `json:"is_child"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
}

// People: anyone the family tracks things for (SPEC 3, "Concepts").
//
// Archived rather than deleted, because items recorded against a person must
// keep their history when that person stops being current.
func (q *Queries) CreatePerson(ctx context.Context, arg CreatePersonParams) (Person, error) {
	row := q.db.QueryRow(ctx, createPerson,
		arg.FamilyID,
		arg.Name,
		arg.Birthdate,
		arg.UserID,
		arg.IsChild,
		arg.AvatarUrl,
	)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.Name,
		&i.Birthdate,
		&i.UserID,
		&i.IsChild,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getPerson = `-- name: GetPerson :one
SELECT id, family_id, name, birthdate, user_id, is_child, avatar_url, created_at, updated_at, archived_at
FROM people
WHERE id = $1
  AND family_id = $2
`

type GetPersonParams struct {
	ID       pgtype.UUID `json:"id"`
	FamilyID pgtype.UUID `json:"family_id"`
}

func (q *Queries) GetPerson(ctx context.Context, arg GetPersonParams) (Person, error) {
	row := q.db.QueryRow(ctx, getPerson, arg.ID, arg.FamilyID)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.Name,
		&i.Birthdate,
		&i.UserID,
		&i.IsChild,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const listPeople = `-- name: ListPeople :many
SELECT id, family_id, name, birthdate, user_id, is_child, avatar_url, created_at, updated_at, archived_at
FROM people
WHERE family_id = $1
  AND ($2::boolean OR archived_at IS NULL)
ORDER BY is_child DESC, name, id
`

type ListPeopleParams struct {
	FamilyID        pgtype.UUID `json:"family_id"`
	IncludeArchived bool        `json:"include_archived"`
}

// `include_archived` is a parameter rather than a second query so the list and
// its archived variant cannot drift apart.
func (q *Queries) ListPeople(ctx context.Context, arg ListPeopleParams) ([]Person, error) {
	rows, err := q.db.Query(ctx, listPeople, arg.FamilyID, arg.IncludeArchived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Person{}
	for rows.Next() {
		var i Person
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.Name,
			&i.Birthdate,
			&i.UserID,
			&i.IsChild,
			&i.AvatarUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePerson = `-- name: UpdatePerson :one
UPDATE people
SET name       = coalesce($1, name),
    birthdate  = coalesce($2, birthdate),
    user_id    = coalesce($3, user_id),
    is_child   = coalesce($4, is_child),
    avatar_url = coalesce($5, avatar_url),
    updated_at = now()
WHERE id = $6
  AND family_id = $7
  AND archived_at IS NULL
RETURNING id, family_id, name, birthdate, user_id, is_child, avatar_url, created_at, updated_at, archived_at
`

type UpdatePersonParams struct {
	Name      pgtype.Text `json:"name"`
	Birthdate pgtype.Date `json:"birthdate"`
	UserID    pgtype.UUID `json:"user_id"`
	IsChild   pgtype.Bool `json:"is_child"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
	ID        pgtype.UUID `json:"id"`
	FamilyID  pgtype.UUID `json:"family_id"`
}

// Partial update; a NULL argument leaves its column untouched. `birthdate`,
// `user_id` and `avatar_url` are therefore not clearable through this path,
// which is the right trade while nothing in the UI clears them.
func (q *Queries) UpdatePerson(ctx context.Context, arg UpdatePersonParams) (Person, error) {
	row := q.db.QueryRow(ctx, updatePerson,
		arg.Name,
		arg.Birthdate,
		arg.UserID,
		arg.IsChild,
		arg.AvatarUrl,
		arg.ID,
		arg.FamilyID,
	)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.Name,
		&i.Birthdate,
		&i.UserID,
		&i.IsChild,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}
