// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Operational queries. No tenant data lives here.
	// Round-trip probe: proves the generated code, the pool and Postgres all agree.
	//
	// TENANCY: deliberately not family-scoped, and the only such query in the repo.
	// It is allowlisted by name in sqlc.yaml's `family-scoped` vet rule, so adding
	// another unscoped query requires an obvious, reviewable change to that list.
	GetServerTime(ctx context.Context) (pgtype.Timestamptz, error)
}

var _ Querier = (*Queries)(nil)
