// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: system.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getServerTime = `-- name: GetServerTime :one

SELECT now()::timestamptz AS now
`

// Operational queries. No tenant data lives here.
// Round-trip probe: proves the generated code, the pool and Postgres all agree.
//
// TENANCY: deliberately not family-scoped, and the only such query in the repo.
// It is allowlisted by name in sqlc.yaml's `family-scoped` vet rule, so adding
// another unscoped query requires an obvious, reviewable change to that list.
func (q *Queries) GetServerTime(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getServerTime)
	var now pgtype.Timestamptz
	err := row.Scan(&now)
	return now, err
}
