// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tokens.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :one

INSERT INTO refresh_tokens (user_id, family_id, token_hash, expires_at, user_agent, ip)
VALUES ($1, $2, $3,
        $4, $5, $6)
RETURNING id, user_id, family_id, issued_at, expires_at
`

type CreateRefreshTokenParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	FamilyID  pgtype.UUID        `json:"family_id"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UserAgent pgtype.Text        `json:"user_agent"`
	Ip        *netip.Addr        `json:"ip"`
}

type CreateRefreshTokenRow struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	FamilyID  pgtype.UUID        `json:"family_id"`
	IssuedAt  pgtype.Timestamptz `json:"issued_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// Refresh tokens (SPEC 6, "core-api owns identity").
//
// Rotating refresh tokens with reuse detection: every refresh issues a new
// token and retires the old one. A token that is presented after it has been
// rotated away can only have been captured, so it triggers a revocation of the
// whole account rather than a quiet failure.
//
// Tokens are stored as SHA-256 digests. The raw value exists only in the
// client's cookie.
func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (CreateRefreshTokenRow, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.UserID,
		arg.FamilyID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.Ip,
	)
	var i CreateRefreshTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.IssuedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, user_id, family_id, issued_at, expires_at, rotated_to, revoked_at
FROM refresh_tokens
WHERE token_hash = $1
`

type GetRefreshTokenByHashRow struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	FamilyID  pgtype.UUID        `json:"family_id"`
	IssuedAt  pgtype.Timestamptz `json:"issued_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RotatedTo pgtype.UUID        `json:"rotated_to"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

// `rotated_to` is what makes reuse detectable: a non-NULL value means this
// token was already exchanged, and the presenter should not still have it.
func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash []byte) (GetRefreshTokenByHashRow, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i GetRefreshTokenByHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RotatedTo,
		&i.RevokedAt,
	)
	return i, err
}

const revokeAllUserRefreshTokens = `-- name: RevokeAllUserRefreshTokens :execrows
UPDATE refresh_tokens
SET revoked_at = now()
WHERE user_id = $1
  AND revoked_at IS NULL
`

// TENANCY: deliberately account-wide, and the only write allowlisted in
// sqlc.yaml's `family-scoped` rule.
//
// This runs only on reuse detection. A captured token is evidence that the
// account is compromised, not that one tenant is — so the revocation crosses
// every family the user belongs to, on purpose. Scoping it would leave the
// attacker holding live sessions elsewhere.
func (q *Queries) RevokeAllUserRefreshTokens(ctx context.Context, userID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAllUserRefreshTokens, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :execrows
UPDATE refresh_tokens
SET revoked_at = now()
WHERE id = $1
  AND family_id = $2
  AND revoked_at IS NULL
`

type RevokeRefreshTokenParams struct {
	ID       pgtype.UUID `json:"id"`
	FamilyID pgtype.UUID `json:"family_id"`
}

// Sign-out. Scoped to the session's family so a token can only ever be
// revoked by the tenant it was issued for.
func (q *Queries) RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRefreshToken, arg.ID, arg.FamilyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rotateRefreshToken = `-- name: RotateRefreshToken :execrows
UPDATE refresh_tokens
SET rotated_to = $1,
    revoked_at = now()
WHERE id = $2
  AND family_id = $3
  AND revoked_at IS NULL
`

type RotateRefreshTokenParams struct {
	RotatedTo pgtype.UUID `json:"rotated_to"`
	ID        pgtype.UUID `json:"id"`
	FamilyID  pgtype.UUID `json:"family_id"`
}

// Retires a token in favour of its successor. Both columns are set: the
// successor makes reuse detectable, and the revocation keeps the live-token
// index honest.
func (q *Queries) RotateRefreshToken(ctx context.Context, arg RotateRefreshTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, rotateRefreshToken, arg.RotatedTo, arg.ID, arg.FamilyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
