// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByID = `-- name: GetUserByID :one
SELECT id, google_sub, email, display_name, avatar_url, locale, created_at, last_seen_at
FROM users
WHERE id = $1
`

// TENANCY: pre-tenant. Resolves the principal carried by an access token; the
// caller then scopes everything that follows by the token's tenant claim.
func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleSub,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Locale,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const touchUserLastSeen = `-- name: TouchUserLastSeen :exec
UPDATE users
SET last_seen_at = now()
WHERE id = $1
`

// TENANCY: pre-tenant. Presence is a property of the account, not of a tenant.
func (q *Queries) TouchUserLastSeen(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchUserLastSeen, id)
	return err
}

const upsertUserByGoogleSub = `-- name: UpsertUserByGoogleSub :one

INSERT INTO users (google_sub, email, display_name, avatar_url)
VALUES ($1, $2, $3, $4)
ON CONFLICT (google_sub) DO UPDATE
SET email        = excluded.email,
    display_name = excluded.display_name,
    avatar_url   = excluded.avatar_url,
    last_seen_at = now()
RETURNING id, google_sub, email, display_name, avatar_url, locale, created_at, last_seen_at
`

type UpsertUserByGoogleSubParams struct {
	GoogleSub   string      `json:"google_sub"`
	Email       string      `json:"email"`
	DisplayName string      `json:"display_name"`
	AvatarUrl   pgtype.Text `json:"avatar_url"`
}

// Identity. `users` is the one global table in the schema: a Google account
// exists before it belongs to any family, so the queries here run *before* a
// tenant is known and cannot be scoped by one.
//
// Every query in this file is therefore named in the `family-scoped` vet rule's
// allowlist in sqlc.yaml. Nothing else in the repo may join that list without
// the same justification: no tenant row is read or written here.
// TENANCY: pre-tenant. Runs on the OAuth callback, before membership is known.
//
// Google's `sub` is the stable identity; email and display name are profile
// data that may change between sign-ins, so they are refreshed every time.
func (q *Queries) UpsertUserByGoogleSub(ctx context.Context, arg UpsertUserByGoogleSubParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUserByGoogleSub,
		arg.GoogleSub,
		arg.Email,
		arg.DisplayName,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleSub,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Locale,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}
